---
# tasks file for blackfire.

- name: Include OS specific vars
  include_vars: "os_family/{{ ansible_os_family }}.yml"

- include: os_family/Debian.yml
  when: ansible_os_family == 'Debian'
  tags: provision

- include: os_family/RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: provision

- name: Install the blackfire-agent package
  package: name=blackfire-agent state=present
  tags: provision

- name: Install the blackfire-php package
  package: name=blackfire-php state=present
  tags: provision

- name: Create agent configuration
  template:
    src=agent.j2
    dest={{ blackfire_directory }}/agent
    owner=0
    group=0
    mode=0644
  register: agent_configuration_state
  tags: configuration

- name: Create CLI tool configuration file
  template:
    src=blackfire.ini.j2
    dest="{{ blackfire_user_directory }}/.blackfire.ini"
    owner="{{ blackfire_user }}"
    mode=0644
  when: blackfire_client_id|default('') != "" and blackfire_client_token|default('') != ""
  tags: configuration

- name: Service blackfire-agent restart
  sudo: true
  service: name=blackfire-agent state=restarted
  notify:
    - restart php-fpm
    - restart apache
  when: agent_configuration_state|changed
  tags: deployment

- name: Restart apache if enable in configuration
  service: name=apache2 state=restarted
  when: blackfire_apache_enable
  tags: deployment
